const IMAGE_MAP = {
  "en-prestijli-yilin-basliklari-yilin-animesi_solo-leveling-a-1-pictures": "img/candidates/en-prestijli-yilin-basliklari-yilin-animesi_solo-leveling-a-1-pictures.png",
  "en-prestijli-yilin-basliklari-yilin-animesi_the-apothecary-diaries-sezon-2-olm-project-no-9": "img/candidates/en-prestijli-yilin-basliklari-yilin-animesi_the-apothecary-diaries-sezon-2-olm-project-no-9.jpg",
  "en-prestijli-yilin-basliklari-yilin-animesi_kaiju-no-8-production-i-g": "img/candidates/en-prestijli-yilin-basliklari-yilin-animesi_kaiju-no-8-production-i-g.jpg",
  "en-prestijli-yilin-basliklari-yilin-animesi_gachiakuta": "img/candidates/en-prestijli-yilin-basliklari-yilin-animesi_gachiakuta.jpg",
  "en-prestijli-yilin-basliklari-yilin-animesi_lord-of-mysteries": "img/candidates/en-prestijli-yilin-basliklari-yilin-animesi_lord-of-mysteries.jpg",
  "en-prestijli-yilin-basliklari-yilin-animesi_to-be-hero-x": "img/candidates/en-prestijli-yilin-basliklari-yilin-animesi_to-be-hero-x.jpg",
  "en-prestijli-yilin-basliklari-yilin-animesi_the-summer-hikaru-died": "img/candidates/en-prestijli-yilin-basliklari-yilin-animesi_the-summer-hikaru-died.jpg",
  "en-prestijli-yilin-basliklari-yilin-animesi_dandadan-sezon-2": "img/candidates/en-prestijli-yilin-basliklari-yilin-animesi_dandadan-sezon-2.jpg",
  "en-prestijli-yilin-basliklari-yilin-animesi_orb-on-the-movements-of-the-earth": "img/candidates/en-prestijli-yilin-basliklari-yilin-animesi_orb-on-the-movements-of-the-earth.jpg",
  "en-prestijli-yilin-basliklari-yilin-animesi_the-fragrant-flower-blooms-with-dignity": "img/candidates/en-prestijli-yilin-basliklari-yilin-animesi_the-fragrant-flower-blooms-with-dignity.jpg",
  "en-prestijli-yilin-basliklari-yilin-animesi_sakamoto-days": "img/candidates/en-prestijli-yilin-basliklari-yilin-animesi_sakamoto-days.png",
  "en-prestijli-yilin-basliklari-yilin-animesi_takopii-no-genzai": "img/candidates/en-prestijli-yilin-basliklari-yilin-animesi_takopii-no-genzai.jpg",
  "en-prestijli-yilin-basliklari-yilin-animesi_boku-no-hero-academia-final-season": "img/candidates/en-prestijli-yilin-basliklari-yilin-animesi_boku-no-hero-academia-final-season.jpg",
  "en-prestijli-yilin-basliklari-yilin-animesi_dr-stone-science-future-part-2": "img/candidates/en-prestijli-yilin-basliklari-yilin-animesi_dr-stone-science-future-part-2.jpg",
  "en-prestijli-yilin-basliklari-yilin-animesi_zenshuu": "img/candidates/en-prestijli-yilin-basliklari-yilin-animesi_zenshuu.jpg",
  "en-prestijli-yilin-basliklari-yilin-animesi_Enen no Shouboutai: San no Shou": "img/candidates/en-prestijli-yilin-basliklari-yilin-animesi_Enen no Shouboutai: San no Shou.jpg",
  "en-prestijli-yilin-basliklari-yilin-animesi_my-dress-up-darling-sezon-2": "img/candidates/en-prestijli-yilin-basliklari-yilin-animesi_my-dress-up-darling-sezon-2.jpg",
  "en-prestijli-yilin-basliklari-yilin-animesi_call-of-the-night-season-2": "img/candidates/en-prestijli-yilin-basliklari-yilin-animesi_call-of-the-night-season-2.jpg",
  "en-prestijli-yilin-basliklari-yilin-animesi_spy-family-season-3": "img/candidates/en-prestijli-yilin-basliklari-yilin-animesi_spy-family-season-3.jpg",
  "en-prestijli-yilin-basliklari-yilin-animesi_lazarus": "img/md3fx6mbxv3f1.jpeg",
  "en-prestijli-yilin-basliklari-yilin-anime-filmi_look-back-tatsuki-fujimoto": "img/candidates/en-prestijli-yilin-basliklari-yilin-anime-filmi_look-back-tatsuki-fujimoto.jpg",
  "en-prestijli-yilin-basliklari-yilin-anime-filmi_chainsaw-man-the-movie-reze-arc": "img/candidates/en-prestijli-yilin-basliklari-yilin-anime-filmi_chainsaw-man-the-movie-reze-arc.png",
  "en-prestijli-yilin-basliklari-yilin-anime-filmi_haikyuu-the-movie-decisive-battle-at-the-garbage-dump": "img/candidates/en-prestijli-yilin-basliklari-yilin-anime-filmi_haikyuu-the-movie-decisive-battle-at-the-garbage-dump.jpg",
  "en-prestijli-yilin-basliklari-yilin-anime-filmi_demon-slayer-infinity-castle-movie": "img/candidates/en-prestijli-yilin-basliklari-yilin-anime-filmi_demon-slayer-infinity-castle-movie.jpg",
  "en-prestijli-yilin-basliklari-yilin-anime-filmi_kimi-no-iro-the-colors-within": "img/candidates/en-prestijli-yilin-basliklari-yilin-anime-filmi_kimi-no-iro-the-colors-within.jpg",
  "en-prestijli-yilin-basliklari-yilin-anime-filmi_overlord-the-sacred-kingdom": "img/candidates/en-prestijli-yilin-basliklari-yilin-anime-filmi_overlord-the-sacred-kingdom.png",
  "en-prestijli-yilin-basliklari-yilin-anime-filmi_hyakuemu-100-meters": "img/candidates/en-prestijli-yilin-basliklari-yilin-anime-filmi_hyakuemu-100-meters.png",
  "en-prestijli-yilin-basliklari-yilin-anime-filmi_project-sekai-kowareta-sekai-to-utaenai-miku": "img/candidates/en-prestijli-yilin-basliklari-yilin-anime-filmi_project-sekai-kowareta-sekai-to-utaenai-miku.jpg",
  "en-prestijli-yilin-basliklari-yilin-anime-filmi_baan-otona-no-kyoukai": "img/candidates/en-prestijli-yilin-basliklari-yilin-anime-filmi_baan-otona-no-kyoukai.jpg",
  "en-prestijli-yilin-basliklari-en-iyi-yeni-seri_gachiakuta-bones": "img/candidates/en-prestijli-yilin-basliklari-en-iyi-yeni-seri_gachiakuta-bones.jpg",
  "en-prestijli-yilin-basliklari-en-iyi-yeni-seri_the-fragrant-flower-blooms-with-dignity": "img/candidates/en-prestijli-yilin-basliklari-en-iyi-yeni-seri_the-fragrant-flower-blooms-with-dignity.jpg",
  "en-prestijli-yilin-basliklari-en-iyi-yeni-seri_the-summer-hikaru-died": "img/candidates/en-prestijli-yilin-basliklari-en-iyi-yeni-seri_the-summer-hikaru-died.jpg",
  "en-prestijli-yilin-basliklari-en-iyi-yeni-seri_takopii-no-genzai": "img/candidates/en-prestijli-yilin-basliklari-en-iyi-yeni-seri_takopii-no-genzai.jpg",
  "en-prestijli-yilin-basliklari-en-iyi-yeni-seri_to-be-hero-x": "img/candidates/en-prestijli-yilin-basliklari-en-iyi-yeni-seri_to-be-hero-x.jpg",
  "en-prestijli-yilin-basliklari-en-iyi-yeni-seri_lazarus": "img/md3fx6mbxv3f1.jpeg",
  "en-prestijli-yilin-basliklari-en-iyi-yeni-seri_lord-of-mysteries": "img/candidates/en-prestijli-yilin-basliklari-en-iyi-yeni-seri_lord-of-mysteries.jpg",
  "en-prestijli-yilin-basliklari-en-iyi-yeni-seri_witch-watch": "img/candidates/en-prestijli-yilin-basliklari-en-iyi-yeni-seri_witch-watch.jpg",
  "en-prestijli-yilin-basliklari-en-iyi-yeni-seri_clevatess-majuu-no-ou-to-akago-to-kabane-no-yuusha": "img/candidates/en-prestijli-yilin-basliklari-en-iyi-yeni-seri_clevatess-majuu-no-ou-to-akago-to-kabane-no-yuusha.png",
  "en-prestijli-yilin-basliklari-en-iyi-yeni-seri_zenshuu": "img/candidates/en-prestijli-yilin-basliklari-en-iyi-yeni-seri_zenshuu.jpg",
  "en-prestijli-yilin-basliklari-en-iyi-yeni-seri_vigilante-boku-no-hero-academia-illegals": "img/candidates/en-prestijli-yilin-basliklari-en-iyi-yeni-seri_vigilante-boku-no-hero-academia-illegals.jpg",
  "en-prestijli-yilin-basliklari-en-iyi-yeni-seri_kowloon-generic-romance": "img/candidates/en-prestijli-yilin-basliklari-en-iyi-yeni-seri_kowloon-generic-romance.jpg",
  "en-prestijli-yilin-basliklari-en-iyi-yeni-seri_fujimoto-tatsuki-17-26": "img/candidates/en-prestijli-yilin-basliklari-en-iyi-yeni-seri_fujimoto-tatsuki-17-26.png",
  "en-prestijli-yilin-basliklari-en-iyi-yeni-seri_medalist": "img/candidates/en-prestijli-yilin-basliklari-en-iyi-yeni-seri_medalist.jpg",
  "en-prestijli-yilin-basliklari-en-iyi-yeni-seri_silent-witch-chinmoku-no-majo-no-kakushigoto": "img/candidates/en-prestijli-yilin-basliklari-en-iyi-yeni-seri_silent-witch-chinmoku-no-majo-no-kakushigoto.jpg",
  "en-prestijli-yilin-basliklari-en-iyi-devam-eden-seri_one-piece-egghead-arc": "img/candidates/en-prestijli-yilin-basliklari-en-iyi-devam-eden-seri_one-piece-egghead-arc.jpg",
  "en-prestijli-yilin-basliklari-en-iyi-devam-eden-seri_my-hero-academia-final-season": "img/candidates/en-prestijli-yilin-basliklari-en-iyi-devam-eden-seri_my-hero-academia-final-season.jpg",
  "en-prestijli-yilin-basliklari-en-iyi-devam-eden-seri_re-zero-season-3": "img/candidates/en-prestijli-yilin-basliklari-en-iyi-devam-eden-seri_re-zero-season-3.jpg",
  "en-prestijli-yilin-basliklari-en-iyi-devam-eden-seri_spy-x-family-season-3": "img/candidates/en-prestijli-yilin-basliklari-en-iyi-devam-eden-seri_spy-x-family-season-3.jpg",
  "en-prestijli-yilin-basliklari-en-iyi-devam-eden-seri_to-your-eternity-season-3": "img/candidates/en-prestijli-yilin-basliklari-en-iyi-devam-eden-seri_to-your-eternity-season-3.jpg",
  "en-prestijli-yilin-basliklari-en-iyi-devam-eden-seri_uma-musume-cinderella-gray": "img/candidates/en-prestijli-yilin-basliklari-en-iyi-devam-eden-seri_uma-musume-cinderella-gray.jpg",
  "en-prestijli-yilin-basliklari-en-iyi-devam-eden-seri_kingdom-sezon-6": "img/candidates/en-prestijli-yilin-basliklari-en-iyi-devam-eden-seri_kingdom-sezon-6.png",
  "en-prestijli-yilin-basliklari-en-iyi-devam-eden-seri_the-rising-of-the-shield-hero-sezon-4": "img/candidates/en-prestijli-yilin-basliklari-en-iyi-devam-eden-seri_the-rising-of-the-shield-hero-sezon-4.png",
  "en-prestijli-yilin-basliklari-en-iyi-devam-eden-seri_isekai-quartet-3": "img/candidates/en-prestijli-yilin-basliklari-en-iyi-devam-eden-seri_isekai-quartet-3.jpg",
  "en-prestijli-yilin-basliklari-en-iyi-devam-eden-seri_rascal-does-not-dream-of-bunny-girl-senpai": "img/candidates/en-prestijli-yilin-basliklari-en-iyi-devam-eden-seri_rascal-does-not-dream-of-bunny-girl-senpai.png",
  "en-prestijli-yilin-basliklari-yilin-en-iyi-mangasi_jujutsu-kaisen-modulo": "img/candidates/en-prestijli-yilin-basliklari-yilin-en-iyi-mangasi_jujutsu-kaisen-modulo.jpg",
  "en-prestijli-yilin-basliklari-yilin-en-iyi-mangasi_chainsaw-man": "img/candidates/en-prestijli-yilin-basliklari-yilin-en-iyi-mangasi_chainsaw-man.png",
  "en-prestijli-yilin-basliklari-yilin-en-iyi-mangasi_one-piece": "img/candidates/en-prestijli-yilin-basliklari-yilin-en-iyi-mangasi_one-piece.jpg",
  "en-prestijli-yilin-basliklari-yilin-en-iyi-mangasi_steel-ball-run-jojos-bizarre-adventure-part-7": "img/candidates/en-prestijli-yilin-basliklari-yilin-en-iyi-mangasi_steel-ball-run-jojos-bizarre-adventure-part-7.png",
  "en-prestijli-yilin-basliklari-yilin-en-iyi-mangasi_the-apothecary-diaries": "img/candidates/en-prestijli-yilin-basliklari-yilin-en-iyi-mangasi_the-apothecary-diaries.jpg",
  "en-prestijli-yilin-basliklari-yilin-en-iyi-mangasi_dandadan": "img/candidates/en-prestijli-yilin-basliklari-yilin-en-iyi-mangasi_dandadan.jpg",
  "en-prestijli-yilin-basliklari-yilin-en-iyi-mangasi_gokurakugai": "img/candidates/en-prestijli-yilin-basliklari-yilin-en-iyi-mangasi_gokurakugai.jpg",
  "en-prestijli-yilin-basliklari-yilin-en-iyi-mangasi_futari-switch": "img/candidates/en-prestijli-yilin-basliklari-yilin-en-iyi-mangasi_futari-switch.jpg",
  "en-prestijli-yilin-basliklari-yilin-en-iyi-mangasi_spy-x-family": "img/candidates/en-prestijli-yilin-basliklari-yilin-en-iyi-mangasi_spy-x-family.jpg",
  "en-prestijli-yilin-basliklari-yilin-en-iyi-mangasi_kaiju-no-8": "img/candidates/en-prestijli-yilin-basliklari-yilin-en-iyi-mangasi_kaiju-no-8.jpg",
  "en-prestijli-yilin-basliklari-yilin-en-iyi-mangasi_black-clover": "img/candidates/en-prestijli-yilin-basliklari-yilin-en-iyi-mangasi_black-clover.png",
  "en-prestijli-yilin-basliklari-en-iyi-orijinal-anime_bucchigiri": "img/candidates/en-prestijli-yilin-basliklari-en-iyi-orijinal-anime_bucchigiri.jpg",
  "en-prestijli-yilin-basliklari-en-iyi-orijinal-anime_girls-band-cry": "img/candidates/en-prestijli-yilin-basliklari-en-iyi-orijinal-anime_girls-band-cry.jpg",
  "en-prestijli-yilin-basliklari-en-iyi-orijinal-anime_jellyfish-cant-swim-in-the-night": "img/candidates/en-prestijli-yilin-basliklari-en-iyi-orijinal-anime_jellyfish-cant-swim-in-the-night.jpg",
  "en-prestijli-yilin-basliklari-en-iyi-orijinal-anime_metallic-rouge": "img/candidates/en-prestijli-yilin-basliklari-en-iyi-orijinal-anime_metallic-rouge.jpg",
  "en-prestijli-yilin-basliklari-en-iyi-orijinal-anime_ninja-kamui": "img/candidates/en-prestijli-yilin-basliklari-en-iyi-orijinal-anime_ninja-kamui.png",
  "en-prestijli-yilin-basliklari-en-iyi-orijinal-anime_lazarus": "img/md3fx6mbxv3f1.jpeg",
  "en-prestijli-yilin-basliklari-en-iyi-orijinal-anime_clevatess-majuu-no-ou-to-akago-to-kabane-no-yuusha": "img/candidates/en-prestijli-yilin-basliklari-en-iyi-orijinal-anime_clevatess-majuu-no-ou-to-akago-to-kabane-no-yuusha.png",
  "en-prestijli-yilin-basliklari-en-iyi-orijinal-anime_zenshuu": "img/candidates/en-prestijli-yilin-basliklari-en-iyi-orijinal-anime_zenshuu.jpg",
  "karakter-odakli-en-iyi-ana-karakter_sung-jinwoo-solo-leveling": "img/candidates/karakter-odakli-en-iyi-ana-karakter_sung-jinwoo-solo-leveling.png",
  "karakter-odakli-en-iyi-ana-karakter_maomao-the-apothecary-diaries": "img/candidates/karakter-odakli-en-iyi-ana-karakter_maomao-the-apothecary-diaries.png",
  "karakter-odakli-en-iyi-ana-karakter_kafka-hibino-kaiju-no-8": "img/candidates/karakter-odakli-en-iyi-ana-karakter_kafka-hibino-kaiju-no-8.png",
  "karakter-odakli-en-iyi-ana-karakter_sakamoto-sakamoto-days": "img/candidates/karakter-odakli-en-iyi-ana-karakter_sakamoto-sakamoto-days.png",
  "karakter-odakli-en-iyi-ana-karakter_ken-takakura-dandadan": "img/candidates/karakter-odakli-en-iyi-ana-karakter_ken-takakura-dandadan.png",
  "karakter-odakli-en-iyi-ana-karakter_rudo-gachiakuta": "img/candidates/karakter-odakli-en-iyi-ana-karakter_rudo-gachiakuta.png",
  "karakter-odakli-en-iyi-ana-karakter_marin-kitagawa-my-dress-up-darling": "img/candidates/karakter-odakli-en-iyi-ana-karakter_marin-kitagawa-my-dress-up-darling.png",
  "karakter-odakli-en-iyi-ana-karakter_shinra-kusakabe-fire-force": "img/candidates/karakter-odakli-en-iyi-ana-karakter_shinra-kusakabe-fire-force.png",
  "karakter-odakli-en-iyi-ana-karakter_izuku-midoriya-my-hero-academia": "img/candidates/karakter-odakli-en-iyi-ana-karakter_izuku-midoriya-my-hero-academia.png",
  "karakter-odakli-en-iyi-ana-karakter_x-to-be-hero-x": "img/candidates/karakter-odakli-en-iyi-ana-karakter_x-to-be-hero-x.png",
  "karakter-odakli-en-iyi-ana-karakter_senkuu-ishigami-dr-stone-science-future": "img/candidates/karakter-odakli-en-iyi-ana-karakter_senkuu-ishigami-dr-stone-science-future.png",
  "karakter-odakli-en-iyi-ana-karakter_klein-moretti-lord-of-mysteries": "img/candidates/karakter-odakli-en-iyi-ana-karakter_klein-moretti-lord-of-mysteries.png",
  "karakter-odakli-en-iyi-yardimci-karakter_jinshi-the-apothecary-diaries": "img/candidates/karakter-odakli-en-iyi-yardimci-karakter_jinshi-the-apothecary-diaries.jpg",
  "karakter-odakli-en-iyi-yardimci-karakter_seiko-dandadan": "img/candidates/karakter-odakli-en-iyi-yardimci-karakter_seiko-dandadan.png",
  "karakter-odakli-en-iyi-yardimci-karakter_turbo-granny-dandadan": "img/candidates/karakter-odakli-en-iyi-yardimci-karakter_turbo-granny-dandadan.png",
  "karakter-odakli-en-iyi-yardimci-karakter_enjin-gachiakuta": "img/candidates/karakter-odakli-en-iyi-yardimci-karakter_enjin-gachiakuta.png",
  "karakter-odakli-en-iyi-yardimci-karakter_jin-ho-yu-solo-leveling": "img/candidates/karakter-odakli-en-iyi-yardimci-karakter_jin-ho-yu-solo-leveling.jpg",
  "karakter-odakli-en-iyi-yardimci-karakter_shin-asakura-sakamoto-days": "img/candidates/karakter-odakli-en-iyi-yardimci-karakter_shin-asakura-sakamoto-days.png",
  "karakter-odakli-en-iyi-yardimci-karakter_soushirou-hoshina-kaiju-no-8": "img/candidates/karakter-odakli-en-iyi-yardimci-karakter_soushirou-hoshina-kaiju-no-8.jpg",
  "karakter-odakli-en-iyi-yardimci-karakter_mina-ashiro-kaiju-no-8": "img/candidates/karakter-odakli-en-iyi-yardimci-karakter_mina-ashiro-kaiju-no-8.png",
  "karakter-odakli-en-iyi-yardimci-karakter_shizuka-kuze-takopii-no-genzai": "img/candidates/karakter-odakli-en-iyi-yardimci-karakter_shizuka-kuze-takopii-no-genzai.jpg",
  "karakter-odakli-en-iyi-yardimci-karakter_arthur-boyle-fire-force": "img/candidates/karakter-odakli-en-iyi-yardimci-karakter_arthur-boyle-fire-force.png",
  "karakter-odakli-en-iyi-yardimci-karakter_katsuki-bakugou-my-hero-academia": "img/candidates/karakter-odakli-en-iyi-yardimci-karakter_katsuki-bakugou-my-hero-academia.png",
  "karakter-odakli-en-iyi-yardimci-karakter_anko-uguisu-call-of-the-night": "img/candidates/karakter-odakli-en-iyi-yardimci-karakter_anko-uguisu-call-of-the-night.png",
  "karakter-odakli-en-iyi-antagonist_kei-uzuki-sakamoto-days": "img/candidates/karakter-odakli-en-iyi-antagonist_kei-uzuki-sakamoto-days.jpg",
  "karakter-odakli-en-iyi-antagonist_reze-chainsaw-man-reze-arc": "img/candidates/karakter-odakli-en-iyi-antagonist_reze-chainsaw-man-reze-arc.png",
  "karakter-odakli-en-iyi-antagonist_jabber-wonger-gachiakuta": "img/candidates/karakter-odakli-en-iyi-antagonist_jabber-wonger-gachiakuta.png",
  "karakter-odakli-en-iyi-antagonist_dr-deniz-skinner-lazarus": "img/candidates/karakter-odakli-en-iyi-antagonist_dr-deniz-skinner-lazarus.png",
  "karakter-odakli-en-iyi-antagonist_kibutsuji-muzan-kimetsu-no-yaiba-mugen-rassha-hen": "img/candidates/karakter-odakli-en-iyi-antagonist_kibutsuji-muzan-kimetsu-no-yaiba-mugen-rassha-hen.jpg",
  "karakter-odakli-en-iyi-antagonist_all-for-one-my-hero-academia-final-season": "img/candidates/karakter-odakli-en-iyi-antagonist_all-for-one-my-hero-academia-final-season.jpg",
  "karakter-odakli-en-iyi-antagonist_white-rabbit-fushigi-no-kuni-de-alice-to-dive-in-wonderland": "img/candidates/karakter-odakli-en-iyi-antagonist_white-rabbit-fushigi-no-kuni-de-alice-to-dive-in-wonderland.png",
  "karakter-odakli-en-iyi-antagonist_kaiju-no-9-kaijuu-8-gou-2nd-season": "img/candidates/karakter-odakli-en-iyi-antagonist_kaiju-no-9-kaijuu-8-gou-2nd-season.jpg",
  "karakter-odakli-en-iyi-antagonist_xeno-dr-stone-science-future": "img/candidates/karakter-odakli-en-iyi-antagonist_xeno-dr-stone-science-future.png",
  "karakter-odakli-en-iyi-antagonist_ant-king-houston-wingfield-solo-leveling-2-sezon": "img/candidates/karakter-odakli-en-iyi-antagonist_ant-king-houston-wingfield-solo-leveling-2-sezon.png",
  "karakter-odakli-yilin-cifti_denji-reze-chainsaw-man-reze-arc": [
    "img/candidates/karakter-odakli-yilin-cifti_denji-reze-chainsaw-man-reze-arc_0.png",
    "img/candidates/karakter-odakli-yilin-cifti_denji-reze-chainsaw-man-reze-arc_1.png"
  ],
  "karakter-odakli-yilin-cifti_ken-takakura-momo-ayase-dandadan": [
    "img/candidates/karakter-odakli-yilin-cifti_ken-takakura-momo-ayase-dandadan_0.png",
    "img/candidates/karakter-odakli-yilin-cifti_ken-takakura-momo-ayase-dandadan_1.png"
  ],
  "karakter-odakli-yilin-cifti_maomao-jinshi-the-apothecary-diaries": [
    "img/candidates/karakter-odakli-yilin-cifti_maomao-jinshi-the-apothecary-diaries_0.png",
    "img/candidates/karakter-odakli-yilin-cifti_maomao-jinshi-the-apothecary-diaries_1.jpg"
  ],
  "karakter-odakli-yilin-cifti_kaoruko-waguri-rintarou-tsumugi-fragrant-flower": [
    "img/candidates/karakter-odakli-yilin-cifti_kaoruko-waguri-rintarou-tsumugi-fragrant-flower_0.png",
    "img/candidates/karakter-odakli-yilin-cifti_kaoruko-waguri-rintarou-tsumugi-fragrant-flower_1.jpg"
  ],
  "karakter-odakli-yilin-cifti_marin-kitagawa-wakana-gojou-my-dress-up-darling": [
    "img/candidates/karakter-odakli-yilin-cifti_marin-kitagawa-wakana-gojou-my-dress-up-darling_0.png",
    "img/candidates/karakter-odakli-yilin-cifti_marin-kitagawa-wakana-gojou-my-dress-up-darling_1.png"
  ],
  "karakter-odakli-yilin-cifti_nico-wakatsuki-morihito-otogi-witch-watch": [
    "img/candidates/karakter-odakli-yilin-cifti_nico-wakatsuki-morihito-otogi-witch-watch_0.png",
    "img/candidates/karakter-odakli-yilin-cifti_nico-wakatsuki-morihito-otogi-witch-watch_1.png"
  ],
  "karakter-odakli-yilin-cifti_nazuna-nanakusa-kou-yamori-call-of-the-night": [
    "img/candidates/karakter-odakli-yilin-cifti_nazuna-nanakusa-kou-yamori-call-of-the-night_0.png",
    "img/candidates/karakter-odakli-yilin-cifti_nazuna-nanakusa-kou-yamori-call-of-the-night_1.png"
  ],
  "karakter-odakli-yilin-cifti_sakuta-azusagawa-mai-sakurajima-rascal-does-not-dream-of-santa-claus": [
    "img/candidates/karakter-odakli-yilin-cifti_sakuta-azusagawa-mai-sakurajima-rascal-does-not-dream-of-santa-claus_0.png",
    "img/candidates/karakter-odakli-yilin-cifti_sakuta-azusagawa-mai-sakurajima-rascal-does-not-dream-of-santa-claus_1.png"
  ],
  "karakter-odakli-yilin-cifti_reiko-kujirai-hajime-kudou-kowloon-generic-romance": [
    "img/candidates/karakter-odakli-yilin-cifti_reiko-kujirai-hajime-kudou-kowloon-generic-romance_0.png",
    "img/candidates/karakter-odakli-yilin-cifti_reiko-kujirai-hajime-kudou-kowloon-generic-romance_1.png"
  ],
  "karakter-odakli-yilin-cifti_yoshiki-tsujinaka-hikaru-indou-the-summer-hikaru-died": [
    "img/candidates/karakter-odakli-yilin-cifti_yoshiki-tsujinaka-hikaru-indou-the-summer-hikaru-died_0.jpg",
    "img/candidates/karakter-odakli-yilin-cifti_yoshiki-tsujinaka-hikaru-indou-the-summer-hikaru-died_1.jpg"
  ],
  "karakter-odakli-yilin-cifti_yor-forger-loid-forger-spy-family": [
    "img/candidates/karakter-odakli-yilin-cifti_yor-forger-loid-forger-spy-family_0.png",
    "img/candidates/karakter-odakli-yilin-cifti_yor-forger-loid-forger-spy-family_1.png"
  ],
  "karakter-odakli-yilin-cifti_kiyoka-kudou-miyo-saimori-my-happy-marriage": [
    "img/candidates/karakter-odakli-yilin-cifti_kiyoka-kudou-miyo-saimori-my-happy-marriage_0.png",
    "img/candidates/karakter-odakli-yilin-cifti_kiyoka-kudou-miyo-saimori-my-happy-marriage_1.png"
  ],
  "karakter-odakli-en-iyi-karakter-dizayni_dandadan": "img/candidates/karakter-odakli-en-iyi-karakter-dizayni_dandadan.jpg",
  "karakter-odakli-en-iyi-karakter-dizayni_demon-slayer-kimetsu-no-yaiba-infinity-castle": "img/candidates/karakter-odakli-en-iyi-karakter-dizayni_demon-slayer-kimetsu-no-yaiba-infinity-castle.jpg",
  "karakter-odakli-en-iyi-karakter-dizayni_kaiju-no-8": "img/candidates/karakter-odakli-en-iyi-karakter-dizayni_kaiju-no-8.jpg",
  "karakter-odakli-en-iyi-karakter-dizayni_the-apothecary-diaries": "img/candidates/karakter-odakli-en-iyi-karakter-dizayni_the-apothecary-diaries.jpg",
  "karakter-odakli-en-iyi-karakter-dizayni_gachiakuta": "img/candidates/karakter-odakli-en-iyi-karakter-dizayni_gachiakuta.jpg",
  "karakter-odakli-en-iyi-karakter-dizayni_lazarus": "img/md3fx6mbxv3f1.jpeg",
  "karakter-odakli-en-iyi-karakter-dizayni_dr-stone": "img/candidates/karakter-odakli-en-iyi-karakter-dizayni_dr-stone.jpg",
  "karakter-odakli-en-iyi-karakter-dizayni_spy-x-family": "img/candidates/karakter-odakli-en-iyi-karakter-dizayni_spy-x-family.jpg",
  "karakter-odakli-en-iyi-karakter-dizayni_fire-force": "img/candidates/karakter-odakli-en-iyi-karakter-dizayni_fire-force.jpg",
  "karakter-odakli-en-iyi-karakter-dizayni_solo-leveling-sezon-2": "img/candidates/karakter-odakli-en-iyi-karakter-dizayni_solo-leveling-sezon-2.png",
  "gorsel-isitsel-en-iyi-animasyon_demon-slayer-series-ufotable": "img/candidates/gorsel-isitsel-en-iyi-animasyon_demon-slayer-series-ufotable.jpg",
  "gorsel-isitsel-en-iyi-animasyon_fate-strange-fake-a-1-pictures": "img/candidates/gorsel-isitsel-en-iyi-animasyon_fate-strange-fake-a-1-pictures.png",
  "gorsel-isitsel-en-iyi-animasyon_dandadan-science-saru": "img/candidates/gorsel-isitsel-en-iyi-animasyon_dandadan-science-saru.jpg",
  "gorsel-isitsel-en-iyi-animasyon_solo-leveling-a-1-pictures": "img/candidates/gorsel-isitsel-en-iyi-animasyon_solo-leveling-a-1-pictures.png",
  "gorsel-isitsel-en-iyi-animasyon_to-be-hero-x-pb-animation": "img/candidates/gorsel-isitsel-en-iyi-animasyon_to-be-hero-x-pb-animation.jpg",
  "gorsel-isitsel-en-iyi-animasyon_lord-of-mysteries-bcmay-pictures": "img/candidates/gorsel-isitsel-en-iyi-animasyon_lord-of-mysteries-bcmay-pictures.jpg",
  "gorsel-isitsel-en-iyi-animasyon_lazarus-mappa": "img/md3fx6mbxv3f1.jpeg",
  "gorsel-isitsel-en-iyi-animasyon_gachiakuta-bones-film": "img/candidates/gorsel-isitsel-en-iyi-animasyon_gachiakuta-bones-film.jpg",
  "gorsel-isitsel-en-iyi-acilis-op_kaiju-no-8-aurora": "img/candidates/gorsel-isitsel-en-iyi-acilis-op_kaiju-no-8-aurora.jpg",
  "gorsel-isitsel-en-iyi-acilis-op_solo-leveling-reawaker": "img/candidates/gorsel-isitsel-en-iyi-acilis-op_solo-leveling-reawaker.png",
  "gorsel-isitsel-en-iyi-acilis-op_dandadan-on-the-way": "img/candidates/gorsel-isitsel-en-iyi-acilis-op_dandadan-on-the-way.jpg",
  "gorsel-isitsel-en-iyi-acilis-op_gachiakuta-hugs": "img/candidates/gorsel-isitsel-en-iyi-acilis-op_gachiakuta-hugs.jpg",
  "gorsel-isitsel-en-iyi-acilis-op_chainsaw-man-reze-hen-iris-out": "img/candidates/gorsel-isitsel-en-iyi-acilis-op_chainsaw-man-reze-hen-iris-out.png",
  "gorsel-isitsel-en-iyi-acilis-op_the-apothecary-diaries-hyakka-ryouran": "img/candidates/gorsel-isitsel-en-iyi-acilis-op_the-apothecary-diaries-hyakka-ryouran.jpg",
  "gorsel-isitsel-en-iyi-acilis-op_to-be-hero-x-inertia": "img/candidates/gorsel-isitsel-en-iyi-acilis-op_to-be-hero-x-inertia.jpg",
  "gorsel-isitsel-en-iyi-acilis-op_my-hero-academia-the-revo": "img/candidates/gorsel-isitsel-en-iyi-acilis-op_my-hero-academia-the-revo.jpg",
  "gorsel-isitsel-en-iyi-acilis-op_call-of-the-night-mirage": "img/candidates/gorsel-isitsel-en-iyi-acilis-op_call-of-the-night-mirage.jpg",
  "gorsel-isitsel-en-iyi-acilis-op_witch-watch-watch-me": "img/candidates/gorsel-isitsel-en-iyi-acilis-op_witch-watch-watch-me.jpg",
  "gorsel-isitsel-en-iyi-ending_my-hero-academia-final-season-i": "img/candidates/gorsel-isitsel-en-iyi-ending_my-hero-academia-final-season-i.jpg",
  "gorsel-isitsel-en-iyi-ending_the-summer-hikaru-died-you-are-my-monster": "img/candidates/gorsel-isitsel-en-iyi-ending_the-summer-hikaru-died-you-are-my-monster.jpg",
  "gorsel-isitsel-en-iyi-ending_the-apothecary-diaries-hitorigoto": "img/candidates/gorsel-isitsel-en-iyi-ending_the-apothecary-diaries-hitorigoto.jpg",
  "gorsel-isitsel-en-iyi-ending_to-be-hero-x-kontinuum": "img/candidates/gorsel-isitsel-en-iyi-ending_to-be-hero-x-kontinuum.jpg",
  "gorsel-isitsel-en-iyi-ending_dandadan-season-2-doukashiteru": "img/candidates/gorsel-isitsel-en-iyi-ending_dandadan-season-2-doukashiteru.jpg",
  "gorsel-isitsel-en-iyi-ending_bang-dream-ave-mujica-georgette": "img/candidates/gorsel-isitsel-en-iyi-ending_bang-dream-ave-mujica-georgette.jpg",
  "gorsel-isitsel-en-iyi-ending_my-dress-up-darling-kawaii-kaiwai": "img/candidates/gorsel-isitsel-en-iyi-ending_my-dress-up-darling-kawaii-kaiwai.jpg",
  "gorsel-isitsel-en-iyi-ending_the-apothecary-diaries-shiawase-no-recipe": "img/candidates/gorsel-isitsel-en-iyi-ending_the-apothecary-diaries-shiawase-no-recipe.jpg",
  "gorsel-isitsel-en-iyi-ending_spy-x-family-actor": "img/candidates/gorsel-isitsel-en-iyi-ending_spy-x-family-actor.jpg",
  "gorsel-isitsel-en-iyi-ending_uma-musume-cinderella-gray-futari": "img/candidates/gorsel-isitsel-en-iyi-ending_uma-musume-cinderella-gray-futari.jpg",
  "gorsel-isitsel-en-iyi-dunya-tasarimi_gachiakuta": "img/candidates/gorsel-isitsel-en-iyi-dunya-tasarimi_gachiakuta.jpg",
  "gorsel-isitsel-en-iyi-dunya-tasarimi_kowloon-generic-romance": "img/candidates/gorsel-isitsel-en-iyi-dunya-tasarimi_kowloon-generic-romance.jpg",
  "gorsel-isitsel-en-iyi-dunya-tasarimi_zenshu-ot": "img/candidates/gorsel-isitsel-en-iyi-dunya-tasarimi_zenshu-ot.jpg",
  "gorsel-isitsel-en-iyi-dunya-tasarimi_mobile-suit-gundam-gquuuuuu-x": "img/candidates/gorsel-isitsel-en-iyi-dunya-tasarimi_mobile-suit-gundam-gquuuuuu-x.jpg",
  "gorsel-isitsel-en-iyi-dunya-tasarimi_moonrise": "img/candidates/gorsel-isitsel-en-iyi-dunya-tasarimi_moonrise.jpg",
  "gorsel-isitsel-en-iyi-dunya-tasarimi_lazarus": "img/md3fx6mbxv3f1.jpeg",
  "gorsel-isitsel-en-iyi-dunya-tasarimi_the-apothecary-diaries-season-2": "img/candidates/gorsel-isitsel-en-iyi-dunya-tasarimi_the-apothecary-diaries-season-2.jpg",
  "gorsel-isitsel-en-iyi-dunya-tasarimi_dr-stone-science-future": "img/candidates/gorsel-isitsel-en-iyi-dunya-tasarimi_dr-stone-science-future.jpg",
  "gorsel-isitsel-en-iyi-dunya-tasarimi_my-happy-marriage-season-2": "img/candidates/gorsel-isitsel-en-iyi-dunya-tasarimi_my-happy-marriage-season-2.jpg",
  "tur-bazli-en-iyi-aksiyon_fire-force-season-3": "img/candidates/tur-bazli-en-iyi-aksiyon_fire-force-season-3.jpg",
  "tur-bazli-en-iyi-aksiyon_dandadan-sezon-2": "img/candidates/tur-bazli-en-iyi-aksiyon_dandadan-sezon-2.jpg",
  "tur-bazli-en-iyi-aksiyon_demon-slayer-kimetsu-no-yaiba-hashira-training-arc": "img/candidates/tur-bazli-en-iyi-aksiyon_demon-slayer-kimetsu-no-yaiba-hashira-training-arc.png",
  "tur-bazli-en-iyi-aksiyon_kaiju-no-8": "img/candidates/tur-bazli-en-iyi-aksiyon_kaiju-no-8.jpg",
  "tur-bazli-en-iyi-aksiyon_solo-leveling-sezon-2": "img/candidates/tur-bazli-en-iyi-aksiyon_solo-leveling-sezon-2.png",
  "tur-bazli-en-iyi-aksiyon_wind-breaker": "img/candidates/tur-bazli-en-iyi-aksiyon_wind-breaker.jpg",
  "tur-bazli-en-iyi-aksiyon_chainsaw-man-reze-hen": "img/candidates/tur-bazli-en-iyi-aksiyon_chainsaw-man-reze-hen.png",
  "tur-bazli-en-iyi-aksiyon_sakamoto-days": "img/candidates/tur-bazli-en-iyi-aksiyon_sakamoto-days.png",
  "tur-bazli-en-iyi-aksiyon_gachiakuta": "img/candidates/tur-bazli-en-iyi-aksiyon_gachiakuta.jpg",
  "tur-bazli-en-iyi-romantik_honey-lemon-soda": "img/candidates/tur-bazli-en-iyi-romantik_honey-lemon-soda.jpg",
  "tur-bazli-en-iyi-romantik_kowloon-generic-romance": "img/candidates/tur-bazli-en-iyi-romantik_kowloon-generic-romance.jpg",
  "tur-bazli-en-iyi-romantik_im-getting-married-to-a-girl-i-hate-in-my-class": "img/candidates/tur-bazli-en-iyi-romantik_im-getting-married-to-a-girl-i-hate-in-my-class.jpg",
  "tur-bazli-en-iyi-romantik_the-100-girlfriends-who-really-love-you-season-2": "img/candidates/tur-bazli-en-iyi-romantik_the-100-girlfriends-who-really-love-you-season-2.jpg",
  "tur-bazli-en-iyi-romantik_rascal-does-not-dream-of-santa-claus": "img/candidates/tur-bazli-en-iyi-romantik_rascal-does-not-dream-of-santa-claus.png",
  "tur-bazli-en-iyi-romantik_witch-watch": "img/candidates/tur-bazli-en-iyi-romantik_witch-watch.jpg",
  "tur-bazli-en-iyi-romantik_my-dress-up-darling-season-2": "img/candidates/tur-bazli-en-iyi-romantik_my-dress-up-darling-season-2.jpg",
  "tur-bazli-en-iyi-romantik_the-fragrant-flower-blooms-with-dignity": "img/candidates/tur-bazli-en-iyi-romantik_the-fragrant-flower-blooms-with-dignity.jpg",
  "tur-bazli-en-iyi-komedi_witch-watch": "img/candidates/tur-bazli-en-iyi-komedi_witch-watch.jpg",
  "tur-bazli-en-iyi-komedi_grand-blue-season-2": "img/candidates/tur-bazli-en-iyi-komedi_grand-blue-season-2.jpg",
  "tur-bazli-en-iyi-komedi_city-the-animation": "img/candidates/tur-bazli-en-iyi-komedi_city-the-animation.jpg",
  "tur-bazli-en-iyi-komedi_osomatsu-san-4th-season": "img/candidates/tur-bazli-en-iyi-komedi_osomatsu-san-4th-season.jpg",
  "tur-bazli-en-iyi-komedi_everyday-host": "img/candidates/tur-bazli-en-iyi-komedi_everyday-host.jpg",
  "tur-bazli-en-iyi-slice-of-life_catch-me-at-the-ballpark": "img/candidates/tur-bazli-en-iyi-slice-of-life_catch-me-at-the-ballpark.png",
  "tur-bazli-en-iyi-slice-of-life_welcome-to-the-outcasts-restaurant": "img/candidates/tur-bazli-en-iyi-slice-of-life_welcome-to-the-outcasts-restaurant.jpg",
  "tur-bazli-en-iyi-slice-of-life_yano-kuns-ordinary-days": "img/candidates/tur-bazli-en-iyi-slice-of-life_yano-kuns-ordinary-days.jpg",
  "tur-bazli-en-iyi-slice-of-life_apocalypse-hotel": "img/candidates/tur-bazli-en-iyi-slice-of-life_apocalypse-hotel.png",
  "tur-bazli-en-iyi-slice-of-life_ruri-rocks": "img/candidates/tur-bazli-en-iyi-slice-of-life_ruri-rocks.jpg",
  "tur-bazli-en-iyi-slice-of-life_city-the-animation": "img/candidates/tur-bazli-en-iyi-slice-of-life_city-the-animation.jpg",
  "tur-bazli-en-iyi-slice-of-life_ive-been-killing-slimes-300-years-season-2": "img/candidates/tur-bazli-en-iyi-slice-of-life_ive-been-killing-slimes-300-years-season-2.jpg",
  "tur-bazli-en-iyi-slice-of-life_witch-watch": "img/candidates/tur-bazli-en-iyi-slice-of-life_witch-watch.jpg",
  "tur-bazli-en-iyi-drama_this-monster-wants-to-eat-me": "img/candidates/tur-bazli-en-iyi-drama_this-monster-wants-to-eat-me.jpg",
  "tur-bazli-en-iyi-drama_medalist": "img/candidates/tur-bazli-en-iyi-drama_medalist.jpg",
  "tur-bazli-en-iyi-drama_uma-musume-cinderella-gray": "img/candidates/tur-bazli-en-iyi-drama_uma-musume-cinderella-gray.jpg",
  "tur-bazli-en-iyi-drama_wind-breaker-season-2": "img/candidates/tur-bazli-en-iyi-drama_wind-breaker-season-2.jpg",
  "tur-bazli-en-iyi-drama_lord-of-mysteries": "img/candidates/tur-bazli-en-iyi-drama_lord-of-mysteries.jpg",
  "tur-bazli-en-iyi-drama_kimetsu-no-yaiba-mugenjou-hen-movie-1-akaza-sairai": "img/candidates/tur-bazli-en-iyi-drama_kimetsu-no-yaiba-mugenjou-hen-movie-1-akaza-sairai.jpg",
  "tur-bazli-en-iyi-drama_kaoru-hana-wa-rin-to-saku": "img/candidates/tur-bazli-en-iyi-drama_kaoru-hana-wa-rin-to-saku.jpg",
  "tur-bazli-en-iyi-drama_kusuriya-no-hitorigoto-2nd-season": "img/candidates/tur-bazli-en-iyi-drama_kusuriya-no-hitorigoto-2nd-season.jpg",
  "tur-bazli-best-isekai-anime_welcome-to-japan-ms-elf": "img/candidates/tur-bazli-best-isekai-anime_welcome-to-japan-ms-elf.jpg",
  "tur-bazli-best-isekai-anime_from-bureaucrat-to-villainess-dads-been-reincarnated": "img/candidates/tur-bazli-best-isekai-anime_from-bureaucrat-to-villainess-dads-been-reincarnated.png",
  "tur-bazli-best-isekai-anime_may-i-ask-for-one-final-thing": "img/candidates/tur-bazli-best-isekai-anime_may-i-ask-for-one-final-thing.jpg",
  "tur-bazli-best-isekai-anime_tate-no-yuusha-no-nariagari-season-4": "img/candidates/tur-bazli-best-isekai-anime_tate-no-yuusha-no-nariagari-season-4.png",
  "tur-bazli-best-isekai-anime_zenshuu": "img/candidates/tur-bazli-best-isekai-anime_zenshuu.jpg",
  "tur-bazli-best-isekai-anime_my-status-as-an-assassin-obviously-exceeds-the-heros": "img/candidates/tur-bazli-best-isekai-anime_my-status-as-an-assassin-obviously-exceeds-the-heros.jpg",
  "tur-bazli-best-isekai-anime_the-water-magician": "img/candidates/tur-bazli-best-isekai-anime_the-water-magician.jpg",
  "tur-bazli-best-isekai-anime_i-was-reincarnated-as-the-7th-prince-season-2": "img/candidates/tur-bazli-best-isekai-anime_i-was-reincarnated-as-the-7th-prince-season-2.png",
  "tur-bazli-must-protect-at-all-costs_anya-forger-spy-family-season-2": "img/candidates/tur-bazli-must-protect-at-all-costs_anya-forger-spy-family-season-2.png",
  "tur-bazli-must-protect-at-all-costs_okarun-dandadan": "img/candidates/tur-bazli-must-protect-at-all-costs_okarun-dandadan.png",
  "tur-bazli-must-protect-at-all-costs_anya-forger-spy-family": "img/candidates/tur-bazli-must-protect-at-all-costs_anya-forger-spy-family.png",
  "tur-bazli-must-protect-at-all-costs_angel-chainsaw-man": "img/candidates/tur-bazli-must-protect-at-all-costs_angel-chainsaw-man.png",
  "tur-bazli-must-protect-at-all-costs_takopi-takopii-no-genzai": "img/candidates/tur-bazli-must-protect-at-all-costs_takopi-takopii-no-genzai.png",
  "tur-bazli-must-protect-at-all-costs_nezuko-demon-slayer": "img/candidates/tur-bazli-must-protect-at-all-costs_nezuko-demon-slayer.png",
  "tur-bazli-must-protect-at-all-costs_lishu-the-apothecary-diaries": "img/candidates/tur-bazli-must-protect-at-all-costs_lishu-the-apothecary-diaries.jpg",
  "tur-bazli-must-protect-at-all-costs_haruka-wind-breaker": "img/candidates/tur-bazli-must-protect-at-all-costs_haruka-wind-breaker.png"
};